services:
  main:
    build:
      context: .
      dockerfile: ./apps/hypnos/dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
  cloudinary:
    build:
      context: .
      dockerfile: ./apps/cloudinary/dockerfile
    env_file:
      - .env