
FROM node:20-alpine AS builder

WORKDIR /usr/src/app

COPY package.json .
RUN npm install

COPY apps/cloudinary apps/cloudinary
COPY libs libs
COPY tsconfig.json tsconfig.json
COPY types types
COPY utils utils
COPY prisma prisma


RUN npx prisma generate


RUN npm run build

FROM node:20-alpine AS prod

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app


COPY package.json .
RUN npm install --production


COPY --from=builder /usr/src/app/dist ./dist

COPY --from=builder /usr/src/app/prisma ./prisma
COPY --from=builder /usr/src/app/node_modules/.prisma ./node_modules/.prisma
RUN npx prisma generate


CMD ["node", "dist/apps/cloudinary/src/main"]
